### ISSUE TITLE
Static websites

### ISSUE THREAD

**Issue by arnaudlevy** [w3c/sustyweb#1]
Hi, 

Thanks for this nice work!

There's a big thing missing, regarding static / precompiled websites.
Many websites on the Web could be static, and it would be more secure and lighter to host.
There are plenty of static site generators (SSG) to ease the development, and headless CMS to ease the contribution.

We did explain the benefits [here](https://www.osuny.org/actualites/2023-01-16-quels-sont-les-avantages-des-sites-statiques/) (sorry, french), including a spec from ANSSI (french government security agency) advocating for static whenever possible.

It could be probably mentioned in parts 3 or 4, maybe both.

Yours,
Arnaud

**Comment by AlexDawsonUK** [comment]
Thanks for your comment Arnaud.
It's true we didn't explicitly mention static by name however the following guidelines do define using the most sustainable technique (for the circumstance):
3.7 Rigorously Assess Third-party Services (which would include tooling)
3.15 Use Beneficial JavaScript And Its API's (avoiding unnecessary scripting)
3.21 Align Technical Requirements With Sustainability Goals (make sure your code choices are sustainable)

I agree there is justification for a success criteria to at least identify / clarify the benefit in static over dynamic. It's definitely something we'll examine.

**Comment by arnaudlevy** [comment]
We've been working on the topic for 2 years quite intensely with Osuny, and I'm pretty sure if you don't mention static, most people won't think about it. We've met IT directors who just don't know what it is. 

Available to help on the subject!

**Comment by AlexDawsonUK** [comment]
Section 3.21 "Align Technical Requirements With Sustainability Goals" now has a Success Criteria on "Static VS Dynamic" advocating in favor for static site generators identifying the benefits of their use (and the downsides posed by traditional CMS's). Links (including yours) backing up this claim have been cited. This will be available within the next draft.
