### ISSUE TITLE
Combine overlapping guidelines

### ISSUE THREAD

**Issue by jyasskin** [w3c/sustyweb#100]
It's hard to review the document if it makes the same point in many places.

For example,
* https://w3c.github.io/sustyweb/#minify-your-html-css-and-javascript, https://w3c.github.io/sustyweb/#use-code-splitting-within-projects, https://w3c.github.io/sustyweb/#avoid-code-duplication, https://w3c.github.io/sustyweb/#use-html-elements-correctly, https://w3c.github.io/sustyweb/#compress-your-files, and maybe others are about reducing the bytes sent over the wire. 
* https://w3c.github.io/sustyweb/#avoid-using-deprecated-or-proprietary-code and https://w3c.github.io/sustyweb/#use-the-latest-stable-language-version are about keeping dependencies up to date.
* https://w3c.github.io/sustyweb/#provide-suitable-alternatives-to-web-assets, https://w3c.github.io/sustyweb/#support-non-graphic-ways-to-interact-with-content, https://w3c.github.io/sustyweb/#develop-a-mobile-first-layout, and https://w3c.github.io/sustyweb/#adapt-to-user-preferences are about tailoring sites to individual user needs.

and probably others can be combined too.

**Comment by AlexDawsonUK** [comment]
This has caused a bit of controversy when talking about it with members during meetings as different people have their own ideas as to what feel like similar concerns. I totally get your point that we can and should do some more optimizing but the methods of how these actions are achieved can differ dramatically.

I guess it comes down to individual workflows, but its something we plan to discuss further in future meetings and hopefully come up with some solutions that are more inline with what you have mentioned in the future!

**Comment by AlexDawsonUK** [comment]
As we have made no further progress, I shall close the issue as currently not planned.

However, as we work towards the final v1, we shall re-examine the issue in detail regarding every guideline and SC, which will make the final specification, and the structure in which content is organized for readability.

**Comment by AlexDawsonUK** [comment]
This previously open issue is now [under the review of the Interest Group](https://github.com/w3c/sustainableweb-wsg/issues/5), discussion and resolution will continue there.
