### ISSUE TITLE
[charter] Coordinate with ISO

### ISSUE THREAD

**Issue by jyasskin** [w3c/sustyweb#102]
ISO has a series of standards relating to [environmental protection](https://www.iso.org/ics/13.020/x/) and a [working group on implementing ESG principles](https://www.iso.org/committee/10278813.html). Any working group the W3C charters in this area should coordinate with ISO's WGs and take advantage of work they've already done.

**Comment by AlexDawsonUK** [comment]
We have a member (or two?) actively working with ISO already so this shouldn't be too much trouble (hopefully).

The only issue to contend with is that many ISO specs are not open (and are costly) and we need to be careful about binding our work to any such publications (its one reason why we chose GRI for measurement). Even though ISO is a well reputed body, it could work to the detriment to implementors (who aren't wealthy) if ISO access becomes a requirement.

**Comment by AlexDawsonUK** [comment]
**Note:** We should also co-ordinate with GRI as they are a standards body that our work closely aligns with.

**Comment by AlexDawsonUK** [comment]
This has now been [added to the charter](https://w3c.github.io/sustyweb/wg/charter.html) (5.2).

I should also note that as we will be re-examining GRI scoring when measurability data is better defined and when ISO specs are published we will examine their viability for inclusion within the spec, co-ordination with the two bodies responsible will also occur so this will be an ongoing concern.

As this has been addressed within the charter, I will mark this as resolved. As and when we come to deal with GRI and ISO specs on an individual level, new issues can / will be created to track their progress.

**Comment by AlexDawsonUK** [comment]
This previously open issue is now [under the review of the Interest Group](https://github.com/w3c/sustainableweb-wsg/issues/6), discussion and resolution will continue there.
