### ISSUE TITLE
[charter] A SustyWeb IG would work better to publish a WSG Statement sooner

### ISSUE THREAD

**Issue by tantek** [w3c/sustyweb#105]
Rather than a working group (WG), a Sustainable Web Interest Group (IG) with open participation would better enable the Web Sustainability Guidlines (WSG) to have a larger impact sooner, with broader support.

Proposal: rewrite the current proposed SustyWeb charter as charter for a SustyWeb IG and provide a plan for publishing the WSG as a Note, rapidly iterating similar to how the Community Group is already iterating on the WSG Report, with the eventual goal of publishing an AC-approved W3C Statement to give it more formal standing.

An IG would have less process than a WG. It would for example avoid things like patent-related procedures, disclosures, etc. which should be unnecessary for the WSG.

The IG charter could also define custom success criteria for a WSG Statement that better reflects the varied needs of providing a broad spectrum of sustainability guidelines. A broad set of sustainability guidelines would better achieve sustainability goals than subsetting or restricting the guidelines to only those that pass a more precisely objective testability bar that is expected for purely technical specifications for interoperable independent implementations.

At a high level the WSG is also more similar to the Ethical Web principles, which itself is destined (eventually) for a W3C Statement.

cc: [@ianbjacobs](https://github.com/ianbjacobs), [@caribouW3](https://github.com/caribouW3)

(Originally published at: https://tantek.com/2024/194/b1/sustyweb-ig-wsg-statement)

**Comment by ianbjacobs** [comment]
@tantek, thank you for the discussion and this suggestion. I think this proposal has benefits, especially garnering more support for the charter, so I can support it. There may be downsides to this proposal but they are not jumping out at me. In the future, if the need for a WG arises, we can revisit the question.

I anticipate many (or most) of the group's deliverables would still be relevant in an IG. The group could (and should) request horizontal reviews at some appropriate time in the life of the Note.
