### ISSUE TITLE
[charter] Custom Success Criteria for SustyWeb Interest Group and WSG Statement

### ISSUE THREAD

**Issue by tantek** [w3c/sustyweb#106]
The proposed Working Group (WG) charter contains [boiler-plate "Success Criteria"](https://www.w3.org/2024/06/sustyweb-charter-202406.html#success-criteria) which though excellent for creating strictly technical specifications intended for interoperable implementations that users can choose and use, and are far more strict than necessary for the Web Sustainability Guidelines (WSG), and may instead have the unintended consequence of removing helpful guidance that otherwise cannot pass that high bar of interoperable implementations.

Assuming that [issue 105](https://github.com/w3c/sustyweb/issues/105) is resolved to create an Interest Group (IG) instead of a WG, one subsequent necessary step is to define explicit Success Criteria for the WSG itself.

The Success Criteria for the WSG need to be rewritten to encapsulate consensus goals for the WSG, e.g. having a maximally impactful WSG as soon as possible that can be iteratively improved.

We’d like to see a broad spectrum of any and all possible sustainable web guidance in the guidelines, from known measurable highly impactful techniques, to ideas worth exploring for more sustainable adoption and use of existing web technologies. We leave it up to the editors and contributors to the charter to help define Success Criteria for publishing a WSG Statement that takes into account the goals of the WSG, and the broad spectrum nature of the WSG.

Our hope is that an explicit Success Criteria for a WSG Statement will help guide and focus the IG, help the IG determine when the WSG Note is ready for an Advisory Committee (AC) poll to take it to Statement, as well as provide a methodology for the Advisory Committee (AC) to evaluate a WSG Note to help determine if it passes the criteria that was documented in advance.

(Originally published at: https://tantek.com/2024/204/b2/)

**Comment by AlexDawsonUK** [comment]
As denoted in #105, we have a [charter in progress](https://w3c.github.io/sustyweb/ig/charter.html) and we have as apart of that followed your advice with regards to laying down Success Criteria in addition to re-writing the scope to ensure we meet the feedback from members (as well as meeting our initial goals for the group).

As this is currently in action I'll mark this as complete and feedback can further be provided as required upon the (now created) draft charter).
