### ISSUE TITLE
Living Document (Cross-Pollination)

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#107]
**Issue:** It took decades to get WCAG versions to REC status. We may encounter issues with the need to evolve quickly and update. This may also affect the turnaround for getting IG Statements through the release process as the rapid evolution of the sustainability sector may require updates to certain materials (such as evidence EG. URLs) on a regular basis.

**Solution:** Content that can remain in a static state such as the Guidelines and SCs can remain in the core specification in versioned stasis where release cycles will be naturally slower. Content that requires regular maintainence or updates such as URLs (references) will be offered through cross-referencing from the main specification into Notes, or if conflicts arise and separation of concerns is required the potential for CG Reports can be utilized. Its also been noted that the duel-group status can also function if regulatory issues become a factor and a WG is required to be established at a later date where the WG can handle those aspects of a spec that require the coverage it provides, and an IG can provide coverage of what remains.

**Comment by TzviyaSiegman** [comment]
The timeline for WCAG (which was originally published in the 1990s isn't really relevant. Tech, computing, and the W3C have gotten much faster. WCAG 2.0 to 2.1 took 10 years. 2.2 took 5 years, including a pandemic. This is a different standard, so I don't see the relevance.

**Comment by TzviyaSiegman** [comment]
We might consider making the WSG a living document rather than 1.0. W3C's Process enables a version of living documents. Should we think about this? (cc @tantek)

**Comment by AlexDawsonUK** [comment]
I’m unaware of any W3C specs that have living document status (HTML exists under the WHATWG which is self-structured), so we might be breaking new ground here.

if the option is available I’d be game, I just offered the two tier approach to resolve the issue if living status wasn’t an option for Statements (keep the statements on standard release cycles and have Notes as living full-ins for the more rapidly changing stuff like sources / measurability).

**Comment by tantek** [comment]
I concur with [@TzviyaSiegman](https://github.com/TzviyaSiegman)’s comment, and support making “WSG a living document rather than 1.0”.

Sustainability best practices are constantly evolving, related conditions change year over year (such as how power is generated, how devices consume electricity, etc.), and the CG has strong productive momentum which is worth maintaining and focusing on continuously improving the WSG.

The proposed IG charter could be updated accordingly, listing publishing the WSG as an intended living document rather than focusing on a “1.0” deliverable.

(Originally published at: https://tantek.com/2024/285/t3/)

**Comment by AlexDawsonUK** [comment]
I have added **[Living Document]** to the deliverable to denote its intention going forward.

**Comment by tantek** [comment]
Re-opening since it was removed in https://github.com/w3c/sustyweb/commit/a2357b9ae8361528ca0863b422f17f18a6c31fea

**Comment by AlexDawsonUK** [comment]
As this has been discussed at the IG meeting and the method of delivering the specification has been set out (Living Document with future option for Snapshots as required for issued Note/Statement releases), I will mark this issue as closed and resolved.
