### ISSUE TITLE
ESG Term Usage

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#108]
**Issue:** There has been a certain level of friction around the use of the term ESG (Environmental / Social / Governance) as a defining tenant within the WSGs due to its controversy and being tied into the world of finance rather than pure environmentalism and technology.

**Solution:** As such, a replacement term with a greater level of neutrality and less public debate around its use such as the EEE (Environment / Equity / Economy) or 5P's (Peace & Partnership + Planet / People / Prosperity) would serve equally well.

**Comment by AlexDawsonUK** [comment]
We have (at a meeting) decided upon the use of "People and Planet" as an overarching term to be used, with a broader definition including the above relevant terminology provided in more depth within the glossary.

**Comment by fullo** [comment]
Sustainability is defined by three pillars People, Planet, and Profit/Prosperity. 

I know that the world "profit" can be weaponized, but, as a matter of fact, it is a real pillar of Sustainability. ESG is a projection of PPP onto the real world. 

Talking about Sustainable Web/IT we can't avoid discussions about its Governance part. I think we need to talk about Governance in an explicit way and not as a part of _People and Planet_. 

IMHO this will close the doors to emerging topics such as EU's CRA or [DORA law](https://www.dora-info.eu/) that are part of the equation.

**Comment by AlexDawsonUK** [comment]
Noted, we can use PPP in preference in order to ensure that governance gets a fair seat at the table.
