### ISSUE TITLE
Onboarding Improvements

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#111]
Issue: We have had comments from members of the community and beyond that joining and getting involved (initially) can be a bit difficult and intimidating. There are certain limitations we have as naturally we are bound by using (for example) W3C accounts so we can't improve the signup process - but there are ways we can make things a bit friendlier!

Solution: We have already got a functional wiki with useful information, we allow non-Git contributions (via Issue submissions) such as Google Docs, we have a welcoming Slack community, and more. Other ideas for improvements I have to put into action are as follows.

- A simple website to go either with this CG or to launch with our W3C group to provide handy directional links in a more user-friendly manner than our current system.
- Move our meeting videos from my Google Drive to our GitHub (and potentially convert our meeting Minutes to a friendly HTML format so its all centralized and open within the W3C system.
- Utilizing the GitHub wiki system to provide editorial contribution guidance for anyone wanting to know how everything has been put together!

If anyone has any further thoughts or ideas on how we could improve things for contributors, add them to this thread.

**Comment by airbr** [comment]
Something akin to a custom Linktree website, a one page simple website at any rate with all of the links, that intends to be a durable long lived URL seems like a good idea to me.

**Comment by AlexDawsonUK** [comment]
We now have greater onboarding at both the [Interest Group](https://github.com/w3c/sustainableweb-ig/) and [WSG](https://github.com/w3c/sustainableweb-wsg) GitHub repository readme files and will (once processes are established) improve the contributing documentation to help contributors get involved.

A [web page for onboarding](https://w3c.github.io/sustainableweb-ig/) is also available.

This issue can now be considered closed.
