### ISSUE TITLE
which policies should we add?

### ISSUE THREAD

**Issue by fullo** [w3c/sustyweb#115]
EU has approved DORA ([Digital Operational Resilience Act](https://www.dora-info.eu/)) it is not strictly related to environmental (E) or social (S) activities BUT it is very important regarding the Governance of IT organization. 

Should we add also this kind of law in the policies.html? Maybe adding a column to have explicit the sustainability pillar involved?

Country / Region | Name | Date Enacted | Type | Maturity | Responsible Entity | Pillar (E/S/G)
-- | -- | -- | -- | -- | -- | --

**Comment by AlexDawsonUK** [comment]
Definitely, It'll be added to the next draft.

Regarding the extra column. I think many of the laws blur the line regarding coverage, especially as they have secondary benefits in one or more categories so you could argue many could fall into all three on a technical level, so it could be a redundant feature (or at least far too complex to measure).

**Comment by AlexDawsonUK** [comment]
**Note:** Also have planned [ISO/IEC CD TS 20125](https://www.iso.org/standard/86105.html) set for inclusion in the next update.

**Comment by AlexDawsonUK** [comment]
These have now been added to the [draft supplement](https://w3c.github.io/sustyweb/drafts/policies.html).

I have also included the recent EU AI Act (as its relevant).

The latest updates shall be reflected once the next draft is published. If you can think of anything else that needs including within the document, feel free to add another comment (and I'll reopen the thread) or raise another issue and I'll be sure to include them into the supplement.
