### ISSUE TITLE
Quick Wins

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#12]
Have some method of being able to identify quick wins, or biggest impacts, or highlights within the specification.
Either internally (through filtering) in a future draft, externally ([coming soon](https://sustainablewebdesign.org/)), or through a supplement resource.
Any further ideas are welcome in comments below.

Credit: @cwilso

**Comment by AlexDawsonUK** [comment]
Adding a request for this feature from @andy-blum RE https://andy-blum.com/articles/web-sustainability-guidelines/

**Comment by screenspan** [comment]
I tapped the [JSON API](https://w3c.github.io/sustyweb/guidelines.json) to filter the guidelines by "high impact" and "low effor" or "medium effort" : https://screenspan.net/wsg

Just an idea: 
* Perhaps leave the guidelines at https://w3c.github.io/sustyweb/ in their current form to serve as a reference
* Build a site similar to https://sustainablewebdesign.org/strategies/ that lets you filter and navigate the guidelines

**Comment by AlexDawsonUK** [comment]
Thanks for responding @screenspan. We are already actively working on a redesign of the Sustainable Web Design website which will do precisely what you have mentioned (acting as a navigable, filterable implementation of the specification).

An issue wasn't raised in the GitHub RE this feature previously because it's been on our TODO list from the offset - we just hadn't completed the build until the release of the JSON API which allows the spec and website to keep in sync. As this has now occurred (released 10 days ago), we hope to roll this feature out ASAP.

**Comment by AlexDawsonUK** [comment]
**Note:** As the quick wins will be integrated within the "at-a-glance" document, this issues label has been changed.

**Comment by AlexDawsonUK** [comment]
This has been added into the at-a-glance supplement and will be visible within the next draft.
