### ISSUE TITLE
[charter] SustyWeb IG charter should state intended audience of guidance

### ISSUE THREAD

**Issue by tantek** [w3c/sustyweb#120]
The [SustyWeb IG charter Motivation and Background](https://w3c.github.io/sustyweb/ig/charter.html#background) says: “The Sustainable Web Interest Group will provide evidence-led guidance alongside methods to observe, measure, and improve the sustainability of digital products and services” and then states who will create that guidance.

Before stating who will create the guidance, the charter Background should state who the guidance is intended for. I believe the Web Sustainability Guidelines (WSG) can answer some of this implicitly, however I think it would be helpful for the charter to explicitly state the intended audience. For example (not intended as a specific suggestion), the charter could state something like “This guidance is intended for …” and then perhaps a list of various roles like executives and other decision-makers, managers, designers, developers etc.

I suggest asking the editor(s) of the WSG for a summary of the intended audience, and incorporating that summary into the charter’s Background section. If it would help, I could start a Pull Request with a basic one-sentence suggestion, and invite the editor(s) to make further changes as necessary.

(Originally published at: https://tantek.com/2024/285/b1/)

**Comment by AlexDawsonUK** [comment]
I have provided the required paragraph in background (hopefully providing a comprehensive enough role list).
