### ISSUE TITLE
[charter] SustyWeb IG charter should coordinate with IETF environmental efforts

### ISSUE THREAD

**Issue by tantek** [w3c/sustyweb#121]
The [SustyWeb IG charter Coordination](https://w3c.github.io/sustyweb/ig/charter.html#coordination) section says: “We will also monitor the work of and where appropriate collaborate with standards bodies (external to the W3C) such as those listed below…” and then lists two organizations.

The IETF should be added to this list of standards bodies, perhaps even their [Environmental Impacts of Internet Technology (eimpact)](https://datatracker.ietf.org/group/eimpact/about/) group in particular.

The aspects of coordination could include each group’s email lists, meetings, and perhaps even collaborating on documents.

If it would help, I could start a Pull Request with a basic one-sentence group and coordination description, and invite the editor(s) to make further changes as necessary.

(Originally published at: https://tantek.com/2024/285/b2/)

**Comment by AlexDawsonUK** [comment]
Agreed, I'm a member of the IETF eImpact community as are a few of our contributors so it was an omission not to include this! I've added it into the list as requested.
