### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#14]
We've got a great community of contributors, several of whom are multi-lingual, and a couple have expressed an interest in translating the specification. As such it's prudent to add the feature request to the roadmap.

**Note:** Due to the risk of heavy content changes in it's early stage, we may await the specification to settle into a more stable stage before progressing toward translating. This will be discussed at a CG meeting for deliberation.

**Edit:** Also worth noting that discussion outside Github has pointed that a potential method of translation within the group may utilize the same Google Docs system we followed for the drafting of the guidelines (and then porting them across into ReSpec). This method is more user-friendly and allows for copy-pasting sections as translation progresses.

Credit: @ldevernay, @TzviyaSiegman, @dontcallmedom

**Comment by mgifford** [comment]
Just worth noting that maintaining a translation is a challenge for WCAG.   
  
Perhaps we could have an auto-translated version that is in a Google Doc with comments enabled?   
  
I'd like to have a way to engage non-English speakers in standards development. France in particular has a lot to offer, so seems like we are shooting ourselves in the foot by not having a French version of the draft.

**Comment by fullo** [comment]
I add myself as a contributor to translate it in Italian.

**Comment by AlexDawsonUK** [comment]
This previously open issue is now [under the review of the Interest Group](https://github.com/w3c/sustainableweb-wsg/issues/8), discussion and resolution will continue there.
