### ISSUE TITLE
Typos and suggestions

### ISSUE THREAD

**Issue by yuna-orsini** [w3c/sustyweb#15]
Hello,

Here are a few suggestions about typos I think I've spotted (in the UX section for now).
Please note that English is not my mother tongue.

- "visitor's" is used multiple times instead of "visitors".
- 2.2 -> "evolve it's service" >> "its"
- 2.2 -> "an audiences requirements" >> "audience's"
- 2.2 -> "confusing aspected of the layout >> "aspects"
- 2.9 -> "Prioritizes features that..." >> "Prioritize"
- 2.19 -> "less data than it's rich media alternative" >> "its"

**Comment by AlexDawsonUK** [comment]
Many thanks! We we're aware of the the visitors quirk (https://github.com/w3c/sustyweb/issues/3) but all those are great spots will be resolved within the next draft. If you find anything please do let us know!

**Comment by AlexDawsonUK** [comment]
The fixes to all known issues (detailed above) have been applied.
Changes will be reflected when the next draft is published.
