### ISSUE TITLE
Guidance on cryptographic operations

### ISSUE THREAD

**Issue by OR13** [w3c/sustyweb#2]
I'm interested in sustainable cryptography.

We should not have to choose between security or sustainability, but how do we use evidence to help us discover if the trade offs we have made in other W3C work acceptable?

To kick off the discussion with some examples:

Post Quantum Keys and Signatures are larger and require more energy, but we need to to defend against quantum computers breaking traditional crypto, which will mean impersonation and private data compromise.

Similarly, there are various proposals to selective disclosure and unlinkability. 

What evidence based approaches can we take to recommending crypto suites?

In the digital credentials space (which is addressed by several CGs and WGs, CCG, FedCM, VCWG, DIDWG, etc... ), there are several competing formats, mDoc, JWT/CWT and JSON-LD Data Integrity Proofs.

Each have trade offs, they would have different impacts on sustainability when scaled up.

There seems to be a lot of guidance that applies to web applications that would also apply to digital credentials, I'd like to be able to include informative references the key areas in https://github.com/w3c/vc-jose-cose

How can I improve our document based on the work being done here?

**Comment by AlexDawsonUK** [comment]
As you denoted in #9, in order to resolve I believe this would be best suited in the introduction with advisory guidance for WG's (see TD's, Notes, etc) within it's own section (as you mention) @OR13 to provide the start for cross-panel and multi-disciplinary discussion. So I'll add this to be included within the next draft.

**Comment by OR13** [comment]
I've been working on a respec plugin that uses service workers to benchmark browser crypto, so that you can confirm the performance assertions related to competing formats when reading specs about them.
![Screen Shot 2023-09-17 at 1 43 04 PM](https://github.com/w3c/sustyweb/assets/8295856/4a6360cb-b937-4df4-9dd6-cddfdaa67f32)

The comparison here is not fair to any of these, they were just the easiest for me to test.

They use different curves (which impacts performance), and one of them is doing selective disclosure processing which is expensive, even when compared to RDF Data Set Normalization.

**Comment by OR13** [comment]
Thinking more about the guidance regarding crypto operations in W3C Specs, I think it might be good to make the following recommendations:

1. avoid transforming data before signing and verifying, if it can't be avoided, measure its performance as the size of the input grows, and report on the output size and output runtime in ms.
2. don't compare cross cryptographic primitives (like this does!) at the sane time you compute format specific benchmarks.
3. use native web crypto where possible, this reduces the impact that 3rd party libraries might have on energy time used, for example EdDSA is not well supported in browsers but ES384 is... 

it would be better to compare formats, without switching the underlying crypto out... however that is not always possible, and some vendors make it impossible by design, by shipping credential formats that have no agility, so you cannot compare their performance on the same task across curves.

**Comment by AlexDawsonUK** [comment]
I'm concerned regarding the matter of scope (see issue https://github.com/w3c/sustyweb/issues/13).
Our work needs to be approachable for all web workers, not just people with a passion for cryptography. Of course there are sustainability impacts with this work but we risk alienating the audience if the content is too high concept.
One solution might be that once we have guidance for WG's in place, those groups can add sustainability guidelines into their own work (like cryptography for those whom have that passion), and the WSG's in-turn can cross-reference to such material which expands beyond the general concepts.

**Comment by OR13** [comment]
@AlexDawsonUK I agree, the current draft has language that is specific to rendering, for example: https://w3c.github.io/sustyweb/#success-criterion-control-animation

There will be cases were a W3C spec has no need for guidance on rendering.

As a though experiment, consider the guidance we would have liked to see ship in WebAuthN.
