### ISSUE TITLE
Guidelines JSON API

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#20]
Allowing websites and tools to utilize our guidelines is important going forward.

A proposed solution is the creation of a JSON API which will be kept in sync with the ReSpec (uncompiled) specification. This can be queried via JavaScript and utilized within products such as our [Sustainable Web Design](https://sustainablewebdesign.org/) website, [Ecograder](https://ecograder.com/), and Google Lighthouse.

**Credit:** @timfrick

**Comment by andy-blum** [comment]
For those looking for this information _now_, I wrote a simple scraper: https://gist.github.com/andy-blum/d6d196ed69d9565f24e42198c4628e35

**Comment by AlexDawsonUK** [comment]
The JSON file will be completed in time to be published alongside the second draft.
It will be accessible to be queried as an API via GitHub Pages (or downloadable from our repo).
This file will be kept in-sync with subsequent releases & integrated with our website, and tooling at a later date.
I'll close this as resolved due to the timeline confirmation.
