### ISSUE TITLE
Authoring Tool Guidance

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#22]
While we have already documented issues for the next draft around providing cross-WG (W3C) advisory guidance (https://github.com/w3c/sustyweb/issues/2), and providing a JSON API for third party tooling to utilize our guidelines (https://github.com/w3c/sustyweb/issues/20), this issue has been raised to provide explicit guidance for authoring tools themselves (as opposed to implementors such as web workers).

Such documents have relevance through the W3C via the creation of [ATAG](https://www.w3.org/TR/ATAG20/) and it has been raised that a similar document with advice for creators of tooling would prove additionally useful in rolling out the implementation of the guidelines.

**Credit:** @thibaudcolas

**Comment by AlexDawsonUK** [comment]
**Note:** Adding a connection to possibly include a supplement alike to [UAAG](https://www.w3.org/TR/UAAG10/) alongside ATAG.

**Comment by mgifford** [comment]
UAAG for things like the [Firefox CO2.js integration](https://www.thegreenwebfoundation.org/news/carbon-emissions-in-browser-devtools-firefox-profiler-and-co2-js/)?   
  
Thinking about ATAG.  It would be good to think about Part A & B.   
  
A) How do we make the authoring tool be performant and embrace elements of sustainability.  
  
B) How do we help authors create more sustainable content.  
  
For A, it can be useful to remind evaluators that they should be evaluating the sustainability of the authoring tools. This may include the time that it takes an author to complete the task. Humans have a CO2 impact just by living after all. Use of AI may be another area for consideration. AI is being considered for alt text, and indeed content generation.   
  
For B, I'm thinking of obvious things like checking image sizes. The authoring tool should support images being sized appropriately for the browser, and not being larger than needed. Obviously using newer formants like AVIF and WebP are also part of this.

**Comment by AlexDawsonUK** [comment]
**Update:** Several months ago, the chairs of this group @AlexDawsonUK and @timfrick had a meeting with the [WAI](https://www.w3.org/WAI/) regarding implementation plans of **ATAG** and **UAAG** within **WCAG 3**. After discussing these details we have a rough outline of potentially including non-normative guidance for vendors and tooling within the specification alongside existing guidelines (or in certain cases as additional guidelines) where appropriate using progressive disclosure to avoid confusion for non-agent readers who won't find the material of interest.

This will allow a healthy balance of normative guidelines for implementors and non-normative guidelines for vendors and edge-cases which can be explored further upon interaction with the page (click to view). Plans of what content to include for user-agents and tooling will be discussed and integrated within the specification in due course.
