### ISSUE TITLE
Consider renaming section 4.10 Use Edge Computing

### ISSUE THREAD

**Issue by fershad** [w3c/sustyweb#24]
When I read the title of this section, my mind immediately leapt to edge compute runtimes and platforms like Cloudflare Workers, Deno Deply, Vercel Edge Functions, Netlify Edge Functions and the like. These services allow for bits of compute to run on edge nodes closer to the user to allow for better response times or hyper-localised content among other things.

Reading the section, it seemed to focus on the usage of CDNs to reduce the distance data has to travel over the network, and to benefit from the caching layer that CDNs provide. This isn't quite the same as the "Edge Computing" that I had in mind when reading the section heading.

Renaming the section to "Use CDNs and Edge Caching" could prevent confusion, and allows space for a later exploration into the sustainability profile of Edge Compute such as the runtimes and platforms mentioned above.

**Comment by AlexDawsonUK** [comment]
Agreed this makes sense. I'll tie this into https://github.com/w3c/sustyweb/issues/17 and the change will be made in the next draft.

**Comment by AlexDawsonUK** [comment]
The upcoming draft now states "Consider CDN's And Edge Caching" to better reflect the content as stated by yourself within this issue and soften the wording based upon edge-cases as requested within https://github.com/w3c/sustyweb/issues/17.
