### ISSUE TITLE
Broken / outdated links

### ISSUE THREAD

**Issue by JamesChristie-SustainableUX** [w3c/sustyweb#25]
I'm going through the UX section and testing links. I'll add here. 

2.2
Example 2 box: "test plan" goes to a 410 error on Medium (author deleted post).

2.15 
Focus mode link https://www.green-design.io/focus-mode > https://www.greendesign.io/focus-mode
Dithering images should be https://www.greendesign.io/dithering-images

2.6
Patttterns
 - the link is dead https://patttterns.net/84b89b2059f54c58882c69613e003099

An aside: many of the resources appear in more than one section. If the site used a visited-link hyperlink color, then I'd know I already checked / read that item. Come to think of it - should visited-link-color be a success criteria?

**Comment by AlexDawsonUK** [comment]
Thanks for raising this @JamesChristie-SustainableUX

Broken links are inevitable, especially with a document as large as ours, we are considering the potential for long-term management of the specification for once it gets into a more finalized state (as to whether we manage links outside of the document), however, currently be assured that with each new draft release I've made a note that we will test every reference at the point of release (and resolve or remove errors) to save you a lot of repeat effort!

**Comment by AlexDawsonUK** [comment]
Broken links and redirects have now been resolved and will be reflected within the next draft.
