### ISSUE TITLE
Grammatical Context

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#3]
Kicking off the list of grammar fixes which need to be applied (thanks for the spot @mgifford), we have a number of visitor plural references which appear to be in the singular (visitor's rather than visitors).

Several proof-reads and Text-checking apps didn't catch everything, so that can be addressed in the next draft.
Feel free to add other typos, grammar quirks, etc, either below or as a new issue and we'll be glad to resolve them.

**Comment by thibaudcolas** [comment]
@AlexDawsonUK do you really prefer mentioning typos / grammar issues in GitHub issues rather than a pull request? I have the source HTML open as I read the guidelines, personally it’d take me less effort to fix typos as I see them than report them here with appropriate references – but happy to do whatever works for you.

As an aside I found the "visitor's" one particularly distracting so I’d love to see this fixed sooner so my colleagues don’t get equally distracted when I start recommending they read through the guidelines. And I also wondered why that term was used rather than "users", but that’s another conversation.

**Comment by AlexDawsonUK** [comment]
I replied to you via Slack @thibaudcolas but it might also be helpful for others here also (so I'll repeat the essence of content with some added clarification). The document which currently resides on the GitHub isn't the original source, it's a specially formatted export/compiled version of the W3C ReSpec. What this means is that if and when we release a new draft, any changes made to the existing HTML would be overwritten once the new draft is published. Furthermore, because we want to maintain strict QC over the content (we are creating a specification after all), all changes need to be vetted. It's definitely something we'll be talking about in the next meeting (regarding pull requests), and we are an early stage project so you'll have to forgive us for working out the quirks, but currently we're just using the issue system to maintain a high technical standard over our work.

**Note:** The use of visitors over users was done purposefully. Users automatically makes an assumption (linguistically) that an individual may be a customer of your product or service, whereas visitor more broadly applies to anyone who could access your website or app but not necessarily be a customer.

**Comment by thibaudcolas** [comment]
Thanks @AlexDawsonUK!

**Comment by AlexDawsonUK** [comment]
Following up from this post and connecting it to (https://github.com/w3c/sustyweb/issues/15) I'm attaching a note-to-self that after an intensive run-through the spec I've spotted **100+** spelling & (mostly) grammatical issues requiring resolution for the next draft.

Work on these will be made ASAP so that it can be progressed into the next edition & will reflect within the JSON API.

**Comment by AlexDawsonUK** [comment]
[Attached](https://github.com/w3c/sustyweb/files/12784113/fixes.txt) is a list of the spelling and grammar issues which have thus far been submitted for resolution.
They are currently being instigated and resolved within the second draft of the specification.

**Comment by AlexDawsonUK** [comment]
The fixes to all known issues (detailed above) have been applied.
Changes will be reflected when the next draft is published.
