### ISSUE TITLE
Suggestion: add some nuance in 3.6 avoid code duplication

### ISSUE THREAD

**Issue by marie-ototoi** [w3c/sustyweb#30]
Congratulations and thank you for all this work!

I have a small suggestion: I find the Avoid code duplication guideline could benefit from some nuance.

Of course a good abstraction is much simpler and efficient than duplicated code.

But wrong abstractions can produce code 
- that consume more resources: you might end up with cross conditions in an abstraction, and need to write and run many tests for use cases that actually never happen. 
- that is difficult to maintain: when you need an evolution for one of the cases only, you end up adding more and more conditions, and create complex code with room for bugs. At some point a very simple change takes a lot of time.

It is very easy to get abstractions wrong if you write them too early. 
The WET (Write Everything Twice) and AHA (Avoid Hasty Abstractions) programming principles address those problems, and it might be useful to mention them too.

**Comment by AlexDawsonUK** [comment]
Agreed, code abstraction is a net benefit for reducing the potential for duplicated code. This would make a great success criteria to have individuals examine for potential points where abstraction could be used.
I'll be sure to include it on the list for the next draft.

**Comment by marie-ototoi** [comment]
I am sorry, I am not a native, maybe my message was not understandable. 

I meant the opposite: in many cases abstraction is not a net benefit, and costs more than it saves. IMHO the guideline as it is written might be misleading. It would be useful to mention WET and AHA principles in addition of DRY, and to indicate that code duplication is still better than a wrong abstraction.

**Comment by AlexDawsonUK** [comment]
Thanks for the clarification, now I understand the point you were trying to get across better @marie-ototoi.
Apologies for the misinterpretation! I'll be sure to make the necessary points.

**Comment by AlexDawsonUK** [comment]
Section 3.6 Description has been expanded to mention the importance of good abstraction, and both AHA and WET are identified alongside DRY with a link to their definition. This shall appear in the next draft upon publication.
