### ISSUE TITLE
Typo in 5.17

### ISSUE THREAD

**Issue by jimmccool** [w3c/sustyweb#31]
Success Criterion - Legislation Advocation - my spell checker says there's no 'd' in avocation.

**Comment by AlexDawsonUK** [comment]
Thanks for the submission Jim. I've checked this thoroughly and it appears that the difference between the two words is that [avocate](https://www.oed.com/search/dictionary/?scope=Entries&q=avocate) (outside of the French definition) is an obsolete reference to withdraw a defense, whereas to [advocate](https://www.oed.com/search/dictionary/?scope=Entries&q=advocate) (in both the noun and verb) is to plead or speak in favor of an individual. [[Comparison](https://wikidiff.com/advocate/avocate)]

As this guideline (5.17) is a positive, in reference to employers working to the benefit of their employees, I think the wording choice remains correct? I'll mark this as a non-issue, however if you feel this requires further attention and cite a reference this will be re-examined.

**Comment by jimmccool** [comment]
That seems fine! Great work by the way.

Jim
