### ISSUE TITLE
4.2 / 4.3 (proposal) : add NGINX exemples 

### ISSUE THREAD

**Issue by JulienWilhelm** [w3c/sustyweb#35]
In these criteria, we only provide exemples for Apache2 (with .htaccess). First, it should be precised that these examples concern Apache2. Second, we could add examples for NGINX.

**Comment by AlexDawsonUK** [comment]
As we're trying to keep to one example per guideline (to avoid overwhelming the spec), I've added links to NGINX boilerplates within the text (so that individuals can choose their environment). This will be reflected in the next draft.

**Comment by AlexDawsonUK** [comment]
Some of the examples are now available within the latest draft but there were a couple I ran out of time on, which will be included within the upcoming draft, which will complete the set, ensuring that all instances of Apache have NGINX links.
