### ISSUE TITLE
Opportunity to begin to decolonize perspective on user research

### ISSUE THREAD

**Issue by joshkimux** [w3c/sustyweb#37]
Hi friends, currently I noticed the writing in this piece defaults a western, colonized lens towards research. I'm curious if there's interest in resisting that a bit.

Notably:

- Instead of language framed around conducting research **for** (on) people (objects), what if language focused on conducting research _with_ people?
- Instead of language (like "assess") that hints that power remains within the team (for example, people are often flattened into sticky notes when conducting analysis post research on (not with) them), what if guidance included radical participatory design, intersectional qualitative research, or trauma-informed research methods like member checking, in-vivo analysis, and equitable co-leadership?
- Instead of [language that uses "dark" patterns, what if it used "deceptive" patterns instead?](https://designjustice.org/read-the-principles)
- Instead of resources that often reference favor western, corporate sources (I think the first link is broken too), what if those resources pointed to decolonized or more justice-minded sources?

[I think there's hints of this in 5.18](https://w3c.github.io/sustyweb/#share-decision-making-power-with-appropriate-stakeholders) which I love and wish could be extended into the [research section of this draft in 2.2.](https://w3c.github.io/sustyweb/#assess-and-research-visitor-needs). 

Resisting westernized/decolonized ways of conducting research ON (as opposed to with) communities I believe would lead to more sustainable outcomes. My mind goes to something Victor wrote on his paper on radical participatory design:

> Such a shift benefits not just a specific group, as in HCD, but rather an entire community, society, non-human life like animals and plants, and ecosystems including non-living things such as rivers. Ultimately communities benefit because they have healthier environments and ecosystems, and the design team benefits from learning how to design eco-systematically, relationally, and holistically. Communities near the bottom of social hierarchies tend to be more in tune with the system in which they sit and the various competing needs of both life and non-life in the environment (Gurung, 2020). They bring that knowledge into the process. For example, in a translocal, community design project on water, the community chose this challenge: Ensure a safe, sustainable, equitable, and affordable drinking water future(Roberts, 2017). This design challenge is not anthropocentric, but life-centered. In a current, local, community project where we, the design team, are designing a racially just school community, in addition to human needs, we are looking at the building needs, plant needs, compost needs, and more

Some resources that may be helpful to guide further discussion includes:
- [Victor Udoewa's writing on radical participatory design](https://www.cambridge.org/core/journals/design-science/article/an-introduction-to-radical-participatory-design-decolonising-participatory-design-processes/63F70ECC408844D3CD6C1A5AC7D35F4D)
- [Kelly Ann McKercher's Beyond Sticky Notes](https://www.beyondstickynotes.com/)
- [Sascha Costanza-Chock's Design Justice](https://mitpress.mit.edu/9780262043458/design-justice/)
  - The Design Justice principles may be worth citing/referencing
- [Jennifer Esposito and Venus Evan-Winter's Introduction to Intersectional Qualitative Research](https://us.sagepub.com/en-us/nam/introduction-to-intersectional-qualitative-research/book265127)
- [Elizabeth (Dori) Tunstall's Decolonizing Design](https://mitpress.mit.edu/author/elizabeth-dori-tunstall-38555)

**Comment by AlexDawsonUK** [comment]
This is great stuff, I will address your points in turn:
- Absolutely, we will ensure that the language is changed regarding conducting research.
- I agree that participatory design and it's kin do need to have a seat at the table, though there will naturally always be a place for auditing and assessment. What I'm going todo here is draw up a success criteria to ensure that the things you've mentioned are placed on equal footing.
- Agreed this could do with some clarification, though deceptive design is mentioned briefly I'll make this more prominent.
- Thanks also for the links and the notes on decolonizing design, we're still a draft so naturally the content will reflect this with plenty of updates yet to come.

**Comment by AlexDawsonUK** [comment]
All of the above points have now been addressed. They will appear within the next draft.
