### ISSUE TITLE
Headings case

### ISSUE THREAD

**Issue by j9t** [w3c/sustyweb#39]
The guidelines capitalize headings, alas it seems as simple first-letter capitalization, not as title case. This seems unusual and reads more difficult than standard title case (even with [its variations](https://capitalizemytitle.com/style/NYTimes/)).

There are also inconsistencies, when the first standard W3C sections do use title case (note lowercase “for” and “of”), which are letter capitalized (“For” and “Of”).

How about switching to a title case standard, or even moving to sentence case given that many headings almost represent sentences?

**Comment by AlexDawsonUK** [comment]
Thanks for this spot. We had been aiming to go for title case but errors and inconsistencies had gotten past the first copy edit. The second draft should have all of these ironed out (and a lot more besides).

I'll mark this as resolved as I've gone through the document and made sure the TOC matches title case AP formatting. The changes will be reflected once the second draft becomes publicly available.
