### ISSUE TITLE
Summary table of the guidelines

### ISSUE THREAD

**Issue by gagarine** [w3c/sustyweb#4]
Would love to see a table with all the guidelines with the following columns:

- Guideline number
- Guideline name
- Short description
- Impact
- Effort

**Comment by AlexDawsonUK** [comment]
We are actually working on a live implementation of the guidelines which will be hosted on the [Sustainable Web Design](https://sustainablewebdesign.org/) website, which will allow filtering of the guidelines by tag (categories / user-flow / etc) and more features alongside to make the content more digestible.

But I do also like your idea of a simple table laying out an overview of the guidelines for easy scanning (there's also a potential for checklist features alongside). I'll add it to the list of future content.

**Comment by AlexDawsonUK** [comment]
This supplement will be completed in time to be published alongside the second draft.
This file will be kept in-sync with subsequent releases. I'll close this as resolved due to the timeline confirmation.
