### ISSUE TITLE
Tree Shaking Is Not Great

### ISSUE THREAD

**Issue by srsgores** [w3c/sustyweb#41]
Let's not [advocate for tree-shaking](https://w3c.github.io/sustyweb/#apply-tree-shaking-to-code).  Tree-shaking is a by-product of our convoluted front-end build systems that need not bear relevance to accessibility.  With modern "bundlers" like Vite, we can create and declare our assets **independently**, using the cache as it was intended.

Always better to have multiple CSS and JS files, especially with top-level `await` and ESModules gaining support.  In fact, Vite provides access to modules natively in browsers, removing tree-shaking in some cases from the build step entirely.

With HTTP/2 multiplexing, we don't need tree-shaking, and having more files is actually **faster** and more performant.

Let's not focus on tree-shaking, and let's focus, instead, on **creating more independent assets**.

**Comment by AlexDawsonUK** [comment]
I'm somewhat confused by your issue. We already have a [guideline](https://w3c.github.io/sustyweb/#use-code-splitting-within-projects) in the WSG which explicitly advocates for the modularization of code (which is what you're promoting). Furthermore, with large front-end libraries (many of which do not take advantage of JS modules) still being in extensive use throughout the web ecosystem, the need for tooling to tree-shake (which only means to eliminate unused or redundant code) is still extremely necessary. Additionally, there will be those who may be working on older systems or those who are bound to a build-step process who are not simply able to jump to a modern bundler - and even those who are unable to through a lack of knowledge (such as hobbyists).

I appreciate that you want to advocate for the most performant of options - which is great! But even tooling like Vite recognize that actually, it's not simply a case of one or the other, both have their place and we shouldn't simply forsake a good practice as not needed ([when they are both very much useful](https://vitejs.dev/guide/why.html#why-bundle-for-production)).

I'll mark this as a non-issue for the moment however if you can cite evidence that removing dead and unused code is bad for Web Sustainability (Note: we're not an accessibility group, that's the [WAI](https://www.w3.org/WAI/)), we'll update the next draft as appropriate.
