### ISSUE TITLE
Add metadata to JSON API

### ISSUE THREAD

**Issue by screenspan** [w3c/sustyweb#42]
I tapped the [JSON API](https://w3c.github.io/sustyweb/guidelines.json) to filter the guidelines by "high impact" and "low effort" or "medium effort": https://screenspan.net/wsg

I would have found the following metadata useful:

| Key | Example value |
| -- | -- |
| `lastModified` for the current version of the document | `2023-10-20T09:11:55+0200` |
| `url` for each guideline | `https://w3c.github.io/sustyweb/#apply-tree-shaking-to-code` |

**Comment by AlexDawsonUK** [comment]
This is a great idea, I'll ensure that this rolled out with the next draft.

**Comment by AlexDawsonUK** [comment]
This has now been added into the JSON API and will be reflected once the next draft is published.
