### ISSUE TITLE
New content about a sustainable practice to improve loading medias [2.16] 

### ISSUE THREAD

**Issue by DocRoms** [w3c/sustyweb#45]
**Issue :** 
The section [2.16] `ake a More Sustainable Approach to Media Assets` has interesting criteria:

 - Assess the need for video or sound usage (including only when they add visitor value), and ban
non-informative media (background media) including autoplaying functionality.
 -  Choose the right media to display by compressing according to the visitor's requirements,
selecting the appropriate format, ensuring it works across browsers, and avoiding embedded
player plugins.
 - Increase visitor awareness and control by informing them of the length, format, and weight of the
media; allowing media deactivation, and giving a choice of resolutions; all while providing
alternative resolutions and formats.
 - Set up a media management and use policy to reduce the overall impact of audio and video, with
criteria for media compression and file formats.

But even with these recommendations, it is possible to preload a heavy video in a recent format with a good compression ;) 

**Solution :** 
To add a criterion to propose the use of `facades` ( cf https://developer.chrome.com/en/docs/lighthouse/performance/third-party-facades/ ) to prevent the loading of bigger medias when this one are not used by the users : 
 - Medias requiring a lot of data to be downloaded on the client side (including the media itself) must be loaded via a "facade"

**Note**
 - Don't hesitate to explain the procedure to me if I have followed it incorrectly (the section [contributing guidelines](https://github.com/w3c/sustyweb/blob/ba8d297b35133dfa00b21e812f432ea17e6df25f/CONTRIBUTING.md) is a bit empty :)
 - If you have any further comments, don't hesistate to add it below !
 - Sorry about my english :)

**Comment by AlexDawsonUK** [comment]
I agree entirely (and yes your addition is explained perfectly!), the use of facades should be prioritized in the same way that Lazy-Loading is for images. I'll add this to be included as a Success Criteria within the next draft.

**Comment by AlexDawsonUK** [comment]
This Success Criteria has been added into the specification. It will be available when the next draft is published.
