### ISSUE TITLE
New content to reduce the Impact of Downloadable or Physical Documents [2.23]

### ISSUE THREAD

**Issue by DocRoms** [w3c/sustyweb#47]
**Issue :** 
The section [2.23] `Reduce the Impact of Downloadable or Physical Documents` has interesting criteria:

 - Design documents to limit the printing impact. If the production of paper documents is essential, it
should be designed to limit its impact to the lowest possible. Create a CSS Print stylesheet and
test it with different types of content. Ensure PDF printing is encouraged over paper-based
storage.
- Offer optimized, compressed documents in a variety of accessible file formats.
- Clearly display the document name, a summary, the file size, and the format, allowing the visitor a
choice if possible of both the format, and the language (if not the same as the web page).
Furthermore, be sure to avoid embedding the document within Web pages (provide a direct link to
download or view within the browser instead).

These one are focus on the impact of the front (printing impact, small size of the document, direct link... ). I think it is also useful to reduce the impact on the return side.

**Solution :** 
To add a criterion to propose to optimise the generation of the document on the back side : 
 - Prefer to generate the document one time, (not one time by click on the link)
 - Host it on the free cookies domain.

🎁 On the front side, it can also be useful to specify not to load the document on the page : 
-  Do not display documents within pages [GreenIT.fr / [115 best practices of web Eco-Design rule ](https://github.com/cnumr/best-practices/blob/main/README.en.md#115-best-practices-of-web-eco-design)](https://github.com/cnumr/best-practices/blob/main/chapters/BP_4039_en.md)

**Note**
 - Don't hesitate to explain the procedure to me if I have followed it incorrectly (the section [contributing guidelines](https://github.com/w3c/sustyweb/blob/ba8d297b35133dfa00b21e812f432ea17e6df25f/CONTRIBUTING.md) is a bit empty :)
 - If you have any further comments, don't hesistate to add it below !
 - Sorry about my english :)

**Comment by AlexDawsonUK** [comment]
Agreed this makes sense, I'll add a Success Criteria on Optimizing Delivery covering generation and hosting.
Regarding the front-side matter, it's covered within SC "Labels and Choice" - "Furthermore, be sure to avoid embedding the document within Web pages".
The update will be reflected within the next draft.

**Comment by AlexDawsonUK** [comment]
The Success Criteria has been added to the specification, it will be reflected in the next draft.
