### ISSUE TITLE
Grammar errors for plural words and abbreviations

### ISSUE THREAD

**Issue by YummyBacon5** [w3c/sustyweb#49]
In many places, the plural of a word or abbreviation is incorrect. For example, "API<strong>'s</strong>" instead of "APIs"

Per the [W3C Manual of Style](https://www.w3.org/Guide/manual-of-style/#Spelling).

I've linked the headers as to where these words appear:

- [CDN's](https://w3c.github.io/sustyweb/#consider-cdn-s-and-edge-caching)
- [Network's and CDN's](https://w3c.github.io/sustyweb/#success-criterion-content-delivery-network-s-cdn-s)
- [API's #1](https://w3c.github.io/sustyweb/#use-beneficial-javascript-and-its-api-s)
- [API's #2](https://w3c.github.io/sustyweb/#success-criterion-native-over-custom)
- [API's #3](https://w3c.github.io/sustyweb/#success-criterion-offline-access)
- [Application's and (PWA)'s](https://w3c.github.io/sustyweb/#success-criterion-progressive-web-application-s-pwa-s) (the "s" should be inside the bracket)

There may be more which I haven't found

**Comment by AlexDawsonUK** [comment]
Thanks for this spot, I'll go through the document and ensure that this is taken care of for the next draft.

**Comment by AlexDawsonUK** [comment]
This has now been fixed within the specification and all supplements.
Changes will be reflected within the next published draft.
