### ISSUE TITLE
"Web Workers" may cause confusion

### ISSUE THREAD

**Issue by chrisn** [w3c/sustyweb#53]
Although it should be clear from the context of the document, the term Web Workers may potentially be confused with the web API of the same name: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/, so I suggest rephrasing:

* In [1.1](https://w3c.github.io/sustyweb/#background-on-wsg), it could be replaced by “people building websites” 
* In [1.2.1](https://w3c.github.io/sustyweb/#principles), it could be replaced by “... should mean for website development, attempting …" 
* In [1.2.2](https://w3c.github.io/sustyweb/#guidelines), “that overarches Web worker specialisms” could be removed without losing meaning

**Comment by AlexDawsonUK** [comment]
Agreed. This was also brought up by @ianbjacobs within the draft charter as poor language choice.
As such changes have been made to both documents to ensure avoiding any ambiguity.
I'll mark this as resolved as the next draft (due for release this month) will provide the necessary fix.
