### ISSUE TITLE
Example for 2.4 Consider Sustainability in Early Ideation

### ISSUE THREAD

**Issue by ldevernay** [w3c/sustyweb#55]
Regarding this guideline, I think the wireframe taken as an example shouldn't be one with a video player and social media icons : https://dpbnri2zg3lc2.cloudfront.net/en/wp-content/uploads/old-blog-uploads/versions/samuel-student-wireframe---x----972-715x---.png
More precisely, it should be more sober. I think this kind of resource can induce sustainability.

**Comment by AlexDawsonUK** [comment]
Agreed, having resource intensive (expensive) UI items within the interface doesn't set a good example.
I'll [replace it with this](https://cdn-proxy.slickplan.com/wp-content/uploads/2019/03/hand-drawn-wireframe-1024x683.jpeg) (it's simpler but it uses reusable components you can shuffle about to build an interface which is a nice idea that people could create their own based on this example in real life to reduce screen time).

**Comment by AlexDawsonUK** [comment]
Done. This will be visible in the upcoming draft.
