### ISSUE TITLE
Example for 2.7 Avoid Unnecessary or an Overabundance of Assets

### ISSUE THREAD

**Issue by ldevernay** [w3c/sustyweb#56]
I think the example for this guideline requires some context : https://w3c.github.io/sustyweb/#example-98
As such, I don't know what to think of it. Is it an example for a best practice or a bad practice?

**Comment by AlexDawsonUK** [comment]
Noted. I will ensure that further context will be given to the example to better tie it into the guideline.

**Comment by AlexDawsonUK** [comment]
I have dedicated a paragraph explaining the meaning behind the example to provide clarity.
This will become visible in the upcoming draft.
