### ISSUE TITLE
Spacing needs to be fixed for resources in 2.18 Take a More Sustainable Approach to Typefaces

### ISSUE THREAD

**Issue by ldevernay** [w3c/sustyweb#57]
There appears to be some issues with spacing in bullet points here : https://w3c.github.io/sustyweb/#resources-16

**Comment by AlexDawsonUK** [comment]
This has now been resolved along with some other syntax errors in the documents.
The changes will be reflected on the next draft (due to be published the week of our next meeting 27th).
