### ISSUE TITLE
Additionnal resource for 3.9 Resolve Render Blocking Content

### ISSUE THREAD

**Issue by ldevernay** [w3c/sustyweb#59]
In addition to resources for this guideline, I would mention Islands architecture (loading interactive components only on interaction) : 
https://www.patterns.dev/vanilla/islands-architecture

https://w3c.github.io/sustyweb/#resources-36

**Comment by AlexDawsonUK** [comment]
Awesome! I'll add the resource into the specification.

**Comment by AlexDawsonUK** [comment]
Done. This will appear in the upcoming draft.
