### ISSUE TITLE
Checklist visibility

### ISSUE THREAD

**Issue by www-diogo-in** [w3c/sustyweb#60]
There's a mention of an implementation checklist in an interview but I can't find any quick link on top of the Web Sustainability Guidelines (WSG) 1.0
https://w3c.github.io/sustyweb/

Maybe add a link at the top?

**Comment by AlexDawsonUK** [comment]
Noted. It's held within the Quick reference (which itself has a complete list of the guidelines) but I can see why it would be useful to have it directly linked within the main specification. I'll ensure it's added into the upcoming draft.

**Comment by AlexDawsonUK** [comment]
The link has been added. It will be visible once the upcoming draft is published.

**Comment by www-diogo-in** [comment]
Thank you!

Com os melhores cumprimentos,
Diogo Abrantes da Silva


Tel: +351 915 308 630

Linkedin: linkedin.com/in/dasilvadiogo
Website: www.diogo.in
