### ISSUE TITLE
Marketing and communication view ?

### ISSUE THREAD

**Issue by www-diogo-in** [w3c/sustyweb#61]
As more companies come online and the [digital divide lowers](https://news.un.org/en/tags/digital-divide), digital advertising wil become a heavy weight on a company's/website tool for sustainability. Would it make sense to mention it or add it to the guidelines?

**Comment by www-diogo-in** [comment]
Not sure if pixels and tags from advertising partners should have a specific section or it would fall into a third-party content. What do you think? It's also linked to privacy as well.

**Comment by AlexDawsonUK** [comment]
I think it would fall into third-party content (as SC "Assess Third-parties" explicitly requests using as few as possible to reduce the overall impact - which would hopefully include such features?) - however mentioning them in the Privacy benefits RE "third-party tracking" would make sense (so they at least get a mention), plus adding a couple of resources to back it up will be useful. I'll be sure to do this for the upcoming draft.

**Comment by AlexDawsonUK** [comment]
I've added the extra resources and mentioned the negative effects of pixels and tags to give broader coverage within the specification. It will be visible once the upcoming draft is published. I'll close this issue as complete, but if you can think of anything else that needs adding feel free to drop in additional comments and it'll be addressed in due course!

**Comment by www-diogo-in** [comment]
Hey, yeah I think there's a sustainability side of this. For example, when we use Google Analytics, if we are using a "greener server" we won't control those requests. Also, the website might load extra code and can be unnecessary and have a higher load because it is collecting several data points important to Google and maybe less important to the site owner. 
My ideia would be to try and cut on services like this to avoid extra consumption that we may not need on servers that might not be "green".
