### ISSUE TITLE
View Source Affordance as a sustainable engineering principle

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#62]
Hello fellow contributors,

I wanted to pose a question about one of the guidelines: https://w3c.github.io/sustyweb/#minify-your-html-css-and-javascript

> Whitespace holds no value when it's being presented to the visitor (unless they view the source code), by using minification, valuable data savings can be made which will reduce loading times.

This brief statement seems to basically move past the value that viewing the source code can provide in relation to sustainability in favor of the reduced traffic over the wire because of minification. Reading this without much context one might not take much note at all of the ability to view source code as it is contained in parenthesis and view it as not important to sustainability. 

However, there is some thinking that having viewable source code as part of your application can actually be an engineering principle in it's own right. Some call this the View Source Affordance principle and there are low impact scripts and frameworks which prioritize retaining readability as part of their design, with the idea that people can reuse code and avoid wasted effort. In this way, it seems related to sustainability.

Is it possible we could add a sentence or two about the view source affordance concept, or a resource which explores that? There seems like there could be room here just for a tooltip about the value of reading source code 👍 

Thank you for considering this idea and suggestion, possibly could be split into a different topic or area if its not quite an addition to this guideline. Or just kept as a reference issue in case the the issue comes up in future.

**Comment by airbr** [comment]
Also, in practical terms, 
```
<!doctype html>
<!-- This code was mangled to make it shorter and faster to load.
     You can see the readable version at:
     view-source:https://example.com/index.src.html
-->
```
Would suffice, but we should still and a footnote or reference possibly about this practice!

**Comment by AlexDawsonUK** [comment]
The Success Criteria has been added.
This is now visible in the [draft spec](https://w3c.github.io/sustyweb/drafts/#document-and-share-project-outputs) and will be visible in the public spec in the next major version.
