### ISSUE TITLE
Terminology: abandonment

### ISSUE THREAD

**Issue by thibaudcolas** [w3c/sustyweb#64]
This is relatively minor but I wanted to raise it anyway – in the guidelines, I see the term "abandonment" 15 times. That term feels quite connoted with ideas of emotional distress to me, and also is plain and simple not something I’m used to. So statements about abandonment could perhaps be reworded to use more common terminology / plain language?

As a dev and "English as a second language" person, this is the first time I see "abandonment" used in the digital landscape. I more often see discussions of "conversion", users "dropping off", or "conversion rates" being low or high. I appreciate this isn’t my area of expertise so if the use of the term "abandonment" is crucial that’s very valid, but then perhaps it would warrant an entry in the glossary.

---

Here are specific examples to help – cases where the text could be left as-is but replacing the term with "high conversion rates" or "low conversion rates" depending on the meaning of the sentence:

> […] It can also be used to identify bottlenecks in the user-experience which are causing visitor abandonment. […]
> […] A faster website reduces the chance of abandonment […]
> […] Poorly coded sites may break features for visitors, leading to website abandonment […]

These could be:

> […] It can also be used to identify bottlenecks in the user-experience which are causing low conversion rates. […]
> […] A faster website increases conversion rates […]
> […] Poorly coded sites may break features for visitors, leading to higher conversion rates […]

There are also occasions where the guidelines talk about "churn". In my mind "churn" and abandonment" are more or less the same thing:

> […] a clean, distraction-free layout will reduce churn, page abandonment and the barriers to entry […]
> […] Reduced churn and page abandonment will occur due to the application or website becoming more performant […]

Could be:

> […] a clean, distraction-free layout will improve conversion rates and remove barriers to entry […]
> […] A faster website increases conversion rates. […]

**Comment by AlexDawsonUK** [comment]
Actually, the term abandonment is commonly used in the English speaking world if you decide to dump something from your shopping cart before purchasing. Words can have multiple meanings and in this instance to abandon a purchase is to leave it part way through the process. It's exceptionally commonly used in SEO circles and it's very much used even by everyday people (at least I've heard it being used in the US, UK & Australia).

**Comment by thibaudcolas** [comment]
Thanks @AlexDawsonUK. I see three possible remaining issues which I’d appreciate to see addressed still, or let me know if you don’t consider them to be worth addressing:

- All your provided references are about e-commerce, and shopping carts specifically. Is that term actually appropriate in other contexts? If not, it’d still need changing. If the guidelines using the term "abandonment" are about shopping carts, then I think they should be reworded to "shopping cart abandonment" for clarity.
- Perhaps even if the term is appropriate and used appropriately it’d still be worth replacing it? I’ve personally never worked in e-commerce and don’t see this changing later on in my career. In my opinion the guidelines would be clearer with language that’s more plain or established ("dropping off", "conversion rate", "leaving the page")
- How about a glossary entry?

> unless evidence of better wording can be provided.

What kind of evidence are you after here? I’ve provided five examples of alternative wordings that in my opinion are better, simply by using the generic "conversion rate" term over the "abandonment" term that seems (to me) to be mis-used from e-commerce terminology.

If the number of Google search results is acceptable evidence, I get:

- 17000 results for "page abandonment"
- 56000 results for "site abandonment"
- 1.5M results for "cart abandonment"
- 563M results for "abandonment"

To me this makes it clear that perhaps we shouldn’t be using that terminology if the use of "abandonment" outside of carts is that low?

**Comment by thibaudcolas** [comment]
I also want to note that this is the second time I open an issue and see it closed on short notice. The last time was by you as well, and when I raised that closing something as "not planned" wasn’t in my opinion the right wait to invite further feedback / discussion, [you said yourself](https://github.com/w3c/sustyweb/issues/50#issuecomment-1792819822):

> I agree this can cause confusion so apologies for the misinterpretation, I'll be sure in the future to keep issues open until they have been fully settled.

Again this new issue is marked as "invalid" and "closed as not planned", despite my best efforts to provide constructive feedback and suggest multiple avenues to resolve this (reword, or explain why the term is crucial, or add a glossary entry). If the way I provide feedback is problematic please let me know, as-is it feels to me like I should be spending my time elsewhere.

**Comment by AlexDawsonUK** [comment]
@thibaudcolas this term is used in all sorts of contexts... it's used in programming to abandon things like a call, it's used in marketing for people who abandon or leave a page without joining or doing something you want, it's used in business for people who don't follow through on a sale or a proposition. There's even non technical (IE non Web) areas where it's commonly used. I just used those links as a few cut and paste examples, they are not a whole-market-perspective of every area of which the term is used. The fact is that it's widely used in a range of contexts and is used in everyday language even by non-technical people.

I accept that you're trying to provide constructive feedback but when you're asking us to simply stop using a word in common everyday use without any evidence to justify why (aside from it reminding you of something bad) from one persons perspective, I'm struggling to see the justification for change. In another issue for example I could claim that the word "user" is highly associated in the western world with illegal drugs but that's not a necessary argument for it's removal.

I'll re-open the issue as you wish but the likelihood of this being resolved for inclusion without good evidence (and if anyone else wishes to weigh in on this feel free) is small.

**Comment by thibaudcolas** [comment]
Thank you. I appreciate hearing that the term is used in more contexts than I’m aware. For me personally it still feels like jargon that the guidelines could do without just fine, but I appreciate it might not feel that way for everyone. Or perhaps there’s no specific goal for the guidelines to use plain language where possible as I’ve assumed.

> when you're asking us to simply stop using a word

I suggested two possible resolutions: reword, or keep as-is and add a glossary entry. I’d be very happy to see this resolved with a glossary entry if this seemed like a case where the word is appropriate.

> without any evidence to justify why (aside from it reminding you of something bad) from one persons perspective, I'm struggling to see the justification for change

Again I’m happy to try to provide "evidence" if this is what’s needed? As far as I can tell I have [provided evidence](https://github.com/w3c/sustyweb/issues/64#issuecomment-1885242975) in my follow-up comment to the same nature of what you provided.

Try to appreciate that not all feedback comes fully fleshed-out right from the first post, and that people who haven’t spent as much time with the guidelines as you might not have all the context of the content and process as you. It’s confusing if you’re asked to provide more details and also told your feedback is "invalid", "closed as not planned" all in one go.

> In another issue for example I could claim that the word "user" is highly associated in the western world with illegal drugs but that's not a necessary argument for it's removal.

I’m not sure how to respond to this to be honest or whether I should. Is my request to consider more plain language alternatives / a glossary entry that absurd? If you really wanted to make that kind of claim in good faith and proposed possible resolutions, then that seems like valid feedback to me?

**Comment by AlexDawsonUK** [comment]
I’m not against including a glossary entry for added clarification for both this and issue #65. I’ll discuss this further RE the best approach to resolve this with @timfrick and it will be included in the next draft.

**Comment by AlexDawsonUK** [comment]
I've discussed this with @timfrick and we won't include a glossary entry for this word simply because it's too common a word in the English language to warrant explanation. [Dictionaries](https://dictionary.cambridge.org/dictionary/english/abandon) even use the context to not just abandon a person but places or things (I mean the phrase abandon ship has been around for centuries and is considered plain-english).
This thread has been open for 5 days and no-one else has posted so I'll consider this issue closed.
