### ISSUE TITLE
Terminology: visitors vs. users

### ISSUE THREAD

**Issue by thibaudcolas** [w3c/sustyweb#65]
Similarly to #63 and #64 – I’d like to question the use of the term _visitors_ in the guidelines, as opposed to the much more established "users". I already raised this in #3, and got the following information from @AlexDawsonUK:

> The use of visitors over users was done purposefully. Users automatically makes an assumption (linguistically) that an individual may be a customer of your product or service, whereas visitor more broadly applies to anyone who could access your website or app but not necessarily be a customer.
> @AlexDawsonUK – in [#3 Grammatical Context](https://github.com/w3c/sustyweb/issues/3#issuecomment-1731024828)

I appreciate there’s been pre-existing discussions about this but I thought I’d raise it anyway because I still find it problematic after having been told that rationale. I find the use of the term "visitor" problematic for three reasons, in order of importance:

1. It’s distracting, as I rarely see it. I rarely see it used as an alternative to "user", in my work with User Experience people, User Research people, User Interface designers and developers. The other W3C efforts I’m familiar with like [WCAG](https://www.w3.org/TR/WCAG22/) and [ATAG](https://www.w3.org/TR/ATAG20/) seem to work well with "user"
2. It’s a poor characterisation of people’s experiences with web apps. When I use e.g. GitHub, I don’t consider myself to be "visiting" GitHub. When I file my taxes, I’m not "visiting" a form. Though I’ve seen use of the term "visitor" for websites and public content, I don’t recall ever seeing it used for web experiences that require accounts in particular.
3. To me, it’s connoted with an idea of a short-term and likely one-off interaction. Which is at odds with how a lot of the web works (social media in particular)

I also disagree with the rationale shared above that users implies someone is a customer. There are different types of users just like there are different types of visitors, some of which are customers. I can be a "user" of e.g. GitHub certainly without paying for it and also without having an account there.

---

I‘d recommend giving more consideration to using the more generic "user", unless there really is some fundamental reason why sustainability guidelines would be better seen through the lense of "visitors". If so, I think this would be worth a glossary entry to explain the use of the term, or perhaps even a word in the introduction.

**Comment by AlexDawsonUK** [comment]
Adding further clarification, I have been using a mixture of user and visitor throughout the specification:

- User in cases where an individual interacts or is likely to utilize the product or service.
- Visitor in other cases where they may just be passing by the website (as this leaves a gap for non-interaction).

I feel this leaves a sensible balance without making assumptions as to what the individual will do with their session. I understand you may find it distracting but it is a term which is utilized in the industry and I still feel strongly there is justification for its inclusion.

**Comment by AlexDawsonUK** [comment]
**Note:** I've referred this to @timfrick for feedback so if he thinks we should consolidate and just use users vs the current mixed model I'll have this reflected in the next draft, either way, hopefully we can have this settled with another voice.

**Comment by thibaudcolas** [comment]
Thanks @AlexDawsonUK! A mixture makes sense to me, but in that case I might report specific scenarios where I don’t think the right term is in use. Or if we expect the two terms to be mutually exclusive, then there are occasions were both need to be used for clarity.

See for example: [2.2 Assess and Research Visitor Needs](https://w3c.github.io/sustyweb/#x2-2-assess-and-research-visitor-needs) & [](https://w3c.github.io/sustyweb/#x2-3-research-non-visitor-s-needs) – should be "user" in my opinion? presumably those guidelines aren’t specifically about people passing by. The term "visitor needs" has quite a bit of use in the guideline, which to me should really be "user needs" or "user and visitor needs" if we really want to make the distinction.

**Comment by AlexDawsonUK** [comment]
I've added a glossary term to clarify Visitors Vs Users (in context of the specification).
This is now visible in the [living specification](https://w3c.github.io/sustyweb/drafts/#glossary) and will be visible in the next public draft.
