### ISSUE TITLE
Charter: Do we want to primarily use a mailing list for discussions?

### ISSUE THREAD

**Issue by mgifford** [w3c/sustyweb#69]
Looking at https://w3c.github.io/sustyweb/wg/charter.html

This isn't how we've communicated (partly because we don't have this mailing list at this point). 

"This group primarily conducts its technical work on the public mailing list [public-[email-list]@w3.org](mailto:public-[email-list]@w3.org) ([archive](https://lists.w3.org/Archives/Public/public-[email-list]/)) or on [GitHub issues](https://github.com/w3c/sustyweb/issues). The public is invited to review, discuss and contribute to this work."

But to the existing members want it to be? 

I would prefer to stick to GitHub for decisions and eliminate the reference to old-school mailing lists.

I'd suggest just being clear with folks and changing it to:

"This group primarily conducts its technical work on [GitHub issues](https://github.com/w3c/sustyweb/issues). The public is invited to review, discuss and contribute to this work."

**Comment by AlexDawsonUK** [comment]
I personally like the idea for using email only for event notifications (as it will allow everyone in the group - many who aren't in the Slack) to receive important news. That way general discussion remains in Slack and email is restricted for announcements, though @timfrick would need to agree on this as protocol going forwards.

**Comment by timfrick** [comment]
Thanks @mgifford and @AlexDawsonUK . I'm with you all the way on this. I use the public mailing list only to send important messages to the entire group (usually meeting announcements) and that's it. So I'm all for conducting the technical work on GH.

**Comment by AlexDawsonUK** [comment]
In that case, I'll make relevant updates to the charter and other documents to reflect this to avoid confusion.

**Comment by AlexDawsonUK** [comment]
I've made the charter and spec (+supplement) updates to place less focus on the mailing list for contribution.
