### ISSUE TITLE
New Guideline for Hosting, Infrastructure and Systems: Caching?

### ISSUE THREAD

**Issue by BezPowell** [w3c/sustyweb#72]
`4.2 Optimize Browser Caching` explicitly talks about browser caching (expires headers etc), but also briefly touches upon server side caching. Ideally, both approaches should be used, so this could be added as another guideline or incorporated into the existing one?

Proposed new guideline:

### Cache responses and the results of expensive computation.
Caching the results of expensive computation for future reuse cuts down on the use of server resources and can improve processing times. Depending upon the system used, caching an entire response may bypass the need to interact with the application entirely, as static pages may be served directly by the web server.

#### Success Criterion - Response / Full-page Caching
If using a language or framework that generates pages on-request, cache responses for static pages so that they can be reused for future visitors.

#### Success Criterion - Database / Object Caching
Store the results of expensive computation (for instance large database queries) that are likely to be used across different requests.

I'm essentially thinking aloud with this, so the wording is sub-optimal, but I hope the general idea might be worth consideration?

**Comment by AlexDawsonUK** [comment]
I think the database caching content is partially covered under [3.24](https://w3c.github.io/sustyweb/#run-fewer-simpler-queries-as-possible) - though the Success Criteria could have more broad coverage to not just store them in "variables" but to store them "locally" for repeat usage? As objects can be stored in multiple ways such as JSON or even local databases.

As for the rest, I believe it absolutely could be integrated within the existing guideline so it covers server-side more equally than client-side. This will be added to the list to be included within the next draft.

**Comment by AlexDawsonUK** [comment]
No worries, if you'd like I can make the necessary changes on my next round of edits as I'll be doing some additions anyway?

**Comment by BezPowell** [comment]
> No worries, if you'd like I can make the necessary changes on my next round of edits as I'll be doing some additions anyway?

Sounds good. Thank you!

**Comment by AlexDawsonUK** [comment]
The language within these guidelines and SC have been updated in the living draft.
They will be published in the next version of the specification.
