### ISSUE TITLE
SC "Performance By Default" meaning is unclear

### ISSUE THREAD

**Issue by thibaudcolas** [w3c/sustyweb#79]
Within [2.6 Create a Frictionless Lightweight Experience by Default](https://w3c.github.io/sustyweb/#create-a-frictionless-lightweight-experience-by-default),

> Success Criterion - Performance By Default
> Prioritize performance optimization as a product or service's default approach.

I don’t understand what this means aside from "make your product or service fast".

1. Perhaps "prioritize" could be replaced with something clearer (prioritize over what?)
2. "default approach" – not sure if this is about a service potentially having multiple variations (for example a "light" mode and a "bloated" mode), or different methodological approaches to design / build.

**Comment by AlexDawsonUK** [comment]
Agreed, in-fact 2.26 as a guideline expresses what this SC tries to put across. I’ll make the corrective merge to avoid confusion.

**Comment by AlexDawsonUK** [comment]
I've applied a patch to the [living draft](https://w3c.github.io/sustyweb/drafts/) which resolves this issue, it will appear in the next release of the specification.

**Comment by AlexDawsonUK** [comment]
The fifth draft will be released on the 26th ahead of our meeting on the 28th.
As this issue has remained open for 5 days with no further comments (aside from my resolution) I'll mark it as complete.
