### ISSUE TITLE
Web Sustainability Laws & Policies

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#81]
WAI has a great page which lists relevant legislation and policies in the accessibility sphere. With digital sustainability gathering momentum it would be useful as a resource to have an evergreen list of our own to identify key texts that those complying with the WSGs need to be aware of. My thoughts would be to place this within the Introduction to Web Sustainability document in its own section to give it the coverage it requires.

**Source:** https://www.w3.org/WAI/policies/

**Comment by TzviyaSiegman** [comment]
I think it would be helpful to have a dedicated website not include it in the document. My hope (and suspicion) is that there will be a lot of legislation over the next few years.

**Comment by AlexDawsonUK** [comment]
Noted, I'll build out a dedicated document for it.

**Comment by AlexDawsonUK** [comment]
I've created a [Laws & Policies](https://w3c.github.io/sustyweb/drafts/policies.html) supplement that includes legislation (which have a digital sustainability impact), adding in recognized standards and noteworthy best practices (as they can underpin compliance to regulation).

If members spot missing laws or other links, please feel free to either add them to this thread or submit a new issue.
This supplement will be published alongside the next version of the specification.

**Comment by AlexDawsonUK** [comment]
As Laws & Policies has been updated as per #84 and the layout is pretty much set (though the content is subject to evolution - naturally), I'll mark this as ready as it will be included within this months scheduled version release.
