### ISSUE TITLE
Escaping issue in 5.22 Promote and Implement Responsible Emerging Technology Practices

### ISSUE THREAD

**Issue by acme** [w3c/sustyweb#83]
I noticed an escaping issue in 5.22 Promote and Implement Responsible Emerging Technology Practices, where the double quotes `"` appear escaped on https://w3c.github.io/sustyweb/:

> Organizations must consider, audit, and account for any environmental considerations that may derive from the use of emerging technologies they wish to either promote or implement within a chosen setting. Also note that this should include third-party choices, the \"expense\" (in terms of waste or emissions) of the utilization of the technology to create a desired result, and consequential issues to the environment that may arise from its deployment.

<img width="922" alt="image" src="https://github.com/w3c/sustyweb/assets/19988/e5741ac8-409b-469f-966c-23d9449b6818">

Instead I would expect to see:

> Organizations must consider, audit, and account for any environmental considerations that may derive from the use of emerging technologies they wish to either promote or implement within a chosen setting. Also note that this should include third-party choices, the "expense" (in terms of waste or emissions) of the utilization of the technology to create a desired result, and consequential issues to the environment that may arise from its deployment.

**Comment by AlexDawsonUK** [comment]
Good Spot, thanks @acme. This will be included within our next version release.
I've applied the fix into our [living draft document](https://w3c.github.io/sustyweb/drafts/#success-criterion-environmental-responsibilities) in readiness.
