### ISSUE TITLE
Suggested changes to policies doc

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/sustyweb#84]
As discussed at the 27 March call, I recommend some enhancements to the policies doc:

* For best practices, use "published' instead of "enacted"
* In all the tables, it would be helpful to understand who published the materials and their level of maturity.
* It would be helpful to understand what is meant by "best practices" and how that is established. 

Thanks!

**Comment by AlexDawsonUK** [comment]
[Laws & Policies](https://w3c.github.io/sustyweb/drafts/policies.html) has been updated with all of the information requested (plus some more tweaks besides).
If you spot anything else feel free to let me know!
