### ISSUE TITLE
STAR 1.0 Draft suggestion - Remove "The objective of this technique is to" text from most techniques

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#85]
There is a common pattern that the techniques state under the description what the objective of this technique is. this occurs approximately 158 times in the document. I believe this can be omitted, as it is a very common pattern reading the texts. Possibly it could be summarized once in the preface, that "The objective of the technique is summarized under the description" once.

For example, _WD21-1: Encourage the Use of More Sustainable Creation Toolchains_ is:

> Description
> 
> The objective of this technique is to provide a mechanism of choice...

I believe this could become:

> Description
> 
> Provide a mechanism of choice...

**Comment by AlexDawsonUK** [comment]
Agreed they have become unnecessary. I've removed "The objective of the technique is to" and capitalized the following word without losing any syntactical meaning. This is now visible within the draft of [STAR](https://w3c.github.io/sustyweb/drafts/star.html) for every technique.
