### ISSUE TITLE
STAR 1.0 Draft Suggestion -- WD12-1: Ensure That the Required HTML Elements Are Included; Also capitalization of Doctype generally

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#87]
Hello,

I love this technique, WD12-1: Ensure That the Required HTML Elements Are Included. I feel it could be rephrased a little. Just a suggested edit:

> The objective of this technique is to ensure that the minimum required features are present to render a website or application correctly. This includes but is not limited to a DocType and a series of HTML elements (at a bare minimum). The justification behind this is while a page can technically show without them it is considered bad practice and malformed HTML to not include such features.

Could become:

> Ensure that minimum required features are present to render a website or application correctly. This includes a Doctype and a series of HTML elements. While a page can technically partially work without them it is considered bad practice to not include these features.

My suggestion for this edit is that the actual technique specifies 4 steps to the technique which elaborate on what the possibly shorter description says. I believe the shorter description makes it more concise in some ways. 

Also, the capitalization of DocType in the document could be changed to Doctype I suggest, inline with how MDN seems to handle it:

https://developer.mozilla.org/en-US/docs/Glossary/Doctype

**Comment by AlexDawsonUK** [comment]
Noted, the change has been reflected within the draft of [STAR](https://w3c.github.io/sustyweb/drafts/star.html).
