### ISSUE TITLE
STAR 1.0 Draft Suggestion -- WD08-1: Validate Source Code for Semantic Accuracy minor rewording suggestion

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#88]
1. What is POSH? I think it is an informal term for what we call and should be defining as Semantic HTML. I suggest we just go with Semantic HTML. POSH sounds like a standard below or something when its really just a descriptive acronym? Wikipedia goes with Semantic HTML, MDN uses Semantic HTML with a reference to sometimes called POSH. 

> The objective of this technique is to ensure that HTML meets the criteria for POSH (Plain Old Semantic HTML). This requires using the correct element for the correct purpose and avoiding common syntax mistakes that could be easily correctable. In terms of sustainability, it defines the importance of having code that remains as likely to stay functional in the future as possible.
> 

Could become:

> Ensure that HTML meets the criteria for Semantic HTML. Use the correct semantic element for the correct purpose and avoiding common syntax mistakes that could be easily correctable. In terms of sustainability it is important to have code that remains as likely to stay functional in the future as possible.
> 

The second paragraph I suggest could be omitted or reworded- its that (parenthesis) section at the end that makes me ? the objective.

> For machine testability, examining code for correct element use is a primary step but other features found in validation services such as ensuring elements are closed correctly, that HTML entities are correctly marked up, etc, are of equal importance to avoid rare issues that might occur during the rendering process (if browsers accidentally choose to interpret data incorrectly).

Could become:

> For machine testability, examining code for correct element use is a primary step. Other features found in validation services such as ensuring elements are closed correctly and that HTML entities are correctly marked up help ensure the code will work in all environments as much as possible.

**Comment by AlexDawsonUK** [comment]
> 1. What is POSH? I think it is an informal term for what we call and should be defining as Semantic HTML. I suggest we just go with Semantic HTML. POSH sounds like a standard below or something when its really just a descriptive acronym? Wikipedia goes with Semantic HTML, MDN uses Semantic HTML with a reference to sometimes called POSH.

POSH (Plain Old Semantic HTML) is a pretty well known term in web developer circles for focusing on aspects of the semantic web (it was started in the microformats community), but I agree that it might be a little archaic a term, especially if we want to appeal to a broad house so I've altered the content of the first paragraph as required.

> The second paragraph I suggest could be omitted or reworded- its that (parenthesis) section at the end that makes me ? the objective.

Sorry if it was confusing, I've reworded it slightly to eliminate the parenthesis:

"For machine testability, examining code for correct element use is a primary step. Other features found in validation services such as ensuring elements are closed correctly and that HTML entities are correctly marked up help avoid rare issues that might occur during the rendering process such as web browsers accidentally interpreting data incorrectly."

The changes have been reflected within the draft of [STAR](https://w3c.github.io/sustyweb/drafts/star.html).
