### ISSUE TITLE
How to use document

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#9]
There is a real demand for metrics regarding how to use the document, how to get the best from it, more examples, etc.
Also more information about what sustainability is (including defining the concept better) would be useful.

This could be done either through expanding the introduction to provide more insight or through (as suggested elsewhere) a supplementary document or tutorial (video or otherwise) guiding individuals through the experience offering insights and implementation pathways.

If you have any further details to provide, please offer a comment below.

Credit: @TzviyaSiegman @OR13 @notmariazoe

**Comment by OR13** [comment]
I raised a more specific version of this question here: https://github.com/w3c/sustyweb/issues/2

I am looking for guidance like:

For TR track documents, we recommend a dedicated section on "Sustainability Considerations" similar to "Privacy and Security Considerations". That section SHOULD comment on the following topics: 

- https://w3c.github.io/sustyweb/#business-strategy-and-product-management
- https://w3c.github.io/sustyweb/#hosting-infrastructure-and-systems

Or perhaps it would be better to make a new section that is dedicated to advising on the use with WD / NOTES.

**Comment by notmariazoe** [comment]
We need to understand which metrics are a good proxy for reducing energy consumption on the web for the web dev recommendations, and understanding the impact on carbon footprint of the recos of other areas.

The risk seen of using some of the existing estimator formula approach is that it might be optimizing for a dimension that has conflicting evidence against it. 

As far as I know, the metrics we choose need to have definition in the following categories:

- **Key measures:** What are the indicators that inform the developer about digital sustainability?
- **Consistency and accuracy:** To which degree do these measures yield consistent results regardless of environment?
- **Attribution of impact:** Can we attribute impact to a change in these measures to a specific factor (eg 3P vs 1P, Ads, Front or Back-end)?
- **Best practices and guidance (developer actionability):** What actionable guidance can we offer to developers? Are there continuous integration checks that could be included?
- **Universality of impact:** Are there specific region-based requirements mandated by differences in regulation?

I believe it could be interesting to compare the results of some of the formulas used in the industry with empirical results, and try to understand whether the delta is too big to be an efficient proxy. Thoughts?

**Comment by TzviyaSiegman** [comment]
Thanks @AlexDawsonUK. I think it might be helpful to break this into 2 issues. @notmariazoe has clearly explained a way to work on metrics. 

I think we can write a short section that describes how to dive in. This is included, but not until section 1.2. 

I'm wondering if we might find a way to have a slimmer version of that at the top? We might need to do another edit to remove some of the more narrative aspects of this. Right now, it doesn't read so much as a specification as a story. This isn't bad, but we might want to take another look with standardization eyes (spec specs 😄 )
