### ISSUE TITLE
 Why Carbon aware in Mobile first?

### ISSUE THREAD

**Issue by jeanmonod** [w3c/sustyweb#90]
Hi there,
Thank you so much for all your work so far.
I'm working with the WSG these days and during my exploration if found this [Carbon aware](https://w3c.github.io/sustyweb/#success-criterion-carbon-aware-design) criterion. But it's not really clear to me why this criterion is part of the guideline [Mobile first layout](https://w3c.github.io/sustyweb/#develop-a-mobile-first-layout). I don't really see the connection between them. Shouldn't we create a separated section about carbon aware design?

**Comment by AlexDawsonUK** [comment]
I agree its a bit of an oddity where it currently sits (carbon aware computing IMO would naturally sit better under 4.6 Automate To Fit the Needs as its more focused around shifting workloads around peak usage, renewable availability, etc).

I think when it was drafted members were more focused on how the code of a website adapts to the availability of carbon neutral resources (so during high intensity periods or when renewable aren't available, a Lo-Fi version of a product or service or high impact code mechanics like intensive scripts could be temporarily removed to offset the impact).

Did you have any thoughts as to where it should be placed? If so I'd like to hear your feedback.

**Comment by AlexDawsonUK** [comment]
I've updated the guidance to better reflect this (so its more code and interface relatable)...
> To maximize the use of renewable energy, adapt your website or service to electricity availability using carbon-aware design techniques. This should include using situational design to reduce the codebase or functionality during high-intensity periods or adapting the user-interface to perform better in situations where scaling hardware resources can be avoided to reduce emissions.

Hopefully this better connects the original intentions of the text with its surroundings. As no other comments have been made I'll mark it as complete and note that these updates will be included in this months upcoming release.
