### ISSUE TITLE
New guideline for Business Strategy and Product Management

### ISSUE THREAD

**Issue by iceraluk** [w3c/sustyweb#91]
Firstly, thank you for all the work that has been put in the guidelines, I stumbled upon them while working on a project for my MSc in Environmental Management. I didn't see much about the sustainability of the internet when I first started my MSc in 2020, and while the internet amounts to such a high amount of global emissions, this gives me hope. 

Secondly, apologies if there is already something about this in the guideline or if this has been discussed before, but I didn't find much about it in the guides or GH issues. 

Thirdly, this needs more work, but just to make a start:

Proposed guideline:

**Create a business continuity and disaster recovery plan**

Resilience of the product or service in case of a disaster or emergency should be ensured to restore and maintain operations in case of disruptions.

**Benefits**
- Economic: Will ensure limiting the extent of the disruption.
- Social: Users will have access to potentially vital online services in case of a disaster or emergency.

References:
- https://www.ibm.com/docs/en/i/7.5?topic=system-example-disaster-recovery-plan
- https://sdgs.un.org/topics/disaster-risk-reduction
- related SDGs: https://sdgs.un.org/goals/goal11 + https://sdgs.un.org/goals/goal9
- https://www.iso.org/standard/75106.html

**Comment by AlexDawsonUK** [comment]
Thanks for your suggestion, you're absolutely right that we don't have this in the WSGs (surprisingly).
I've taken what you suggested and drafted [a new guideline](https://w3c.github.io/sustyweb/#create-a-business-continuity-and-disaster-recovery-plan) which hopefully covers this important topic.

I hope it reads well, if you have any further comments or thoughts, feel free to add them - the final version will be be rolled out later this month in our next milestone release.
