### ISSUE TITLE
Normative references need reviewing

### ISSUE THREAD

**Issue by chrisn** [w3c/sustyweb#96]
Normative references should only be used where compliance is also needed to the referenced document. There are many references listed as normative (too many to list individually) that really should be informative

**Comment by AlexDawsonUK** [comment]
Noted, I wasn't aware that this was the case. I will go through them and any that aren't strictly required to comply with the specification will be downgraded to non-normative status by the next published draft. Thanks for the spot!

**Comment by chrisn** [comment]
Wow, that was quick!

**Comment by chrisn** [comment]
Looks good, thanks. I'll close this.
