### ISSUE TITLE
Make sure all success criteria are yes/no questions

### ISSUE THREAD

**Issue by jyasskin** [w3c/sustyweb#97]
For example, ["List the negative external variables and identify where your product's sustainable impact can be diminished"](https://w3c.github.io/sustyweb/#success-criterion-external-variables-machine-testable) can't either succeed or fail for a website, so it can't be a success criterion.

It's possible that you're describing something other than success criteria here, in which case you could fix this by picking a better term.

**Comment by AlexDawsonUK** [comment]
Agreed. I'll go through all the SCs and make sure this is taken care of.

**Comment by AlexDawsonUK** [comment]
I have gone through the [draft specification](https://w3c.github.io/sustyweb/drafts/) and made a huge amount of progress on the editorial language within the SCs to hopefully make them more testable statements. Hopefully I've squashed all of the issues but if any more exist feel free to flag up another issue and point them out! I'll keep an eye out for others as we progress further down the track.

I'll mark this as resolved and all the changes will be made visible with the upcoming public release.
