### ISSUE TITLE
Defend the impact and effort claims

### ISSUE THREAD

**Issue by jyasskin** [w3c/sustyweb#99]
I don't see any assigned meaning for the "low", "medium", and "high" ratings, and no explanation for why violating each guideline has the claimed impact. Why should readers believe these claims?

**Comment by AlexDawsonUK** [comment]
This is one of many pieces of feedback we have taken a lot from (here, the slack conversations, etc).

We absolutely intend to improve upon our measurability credibility and provide a more scientific index than having our current "group consensus" based targets (which granted were fine to get us off the ground, and have subject matter expert backing - but hard numbers is what we need). We are aiming to put in place a way to accurately measure the impact for the WSGs over time and be able to therefore provide a scoring system that is based upon reliable data.

More details will be provided at a later date but suffice to say that measurability is high on our priority list and will hopefully become a key player in our specifications development.

**Comment by andreadavanzo** [comment]
Low, Medium, or High could be translated with

-  RFC: 2119 MAY, SHOULD and MUST. Widely adopted and with reasonable no change of misinterpretation
- Plain Language Alternatives: **required**, **recommended**, and **optional**. This helps avoid misunderstandings for non-technical readers . BTW same words used by NIST SP 800-53
- ISO/IEC: Not my favorite.

I would like to suggest  **required**, **recommended**, and **optional** as first and RFC: 2119 as second

**Comment by AlexDawsonUK** [comment]
This previously open issue is now [under the review of the Interest Group](https://github.com/w3c/sustainableweb-wsg/issues/9), discussion and resolution will continue there.
